"""add attendance rel student str

Revision ID: d8e830ee896b
Revises: 5dc12468f4c9
Create Date: 2025-03-21 14:22:30.885034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e830ee896b'
down_revision: Union[str, None] = '5dc12468f4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
